kconf_check: flag CONFIG options with invalid spaces
Options with spacs around = signs will be droped/ignored by the
kernel.

The audit phase can detect this and warn the user:

  % kconf_check --report -o .kernel-meta/cfg/ \
    linux-qemux86-standard-build/.config `pwd` $cfgs

   [errors (3): .kernel-meta/cfg/fragment_errors.txt
     There are errors withing the config fragments.

  % cat .kernel-meta/cfg/fragment_errors.txt
     Warning: Ignoring "CONFIG_PARAVIRTT_CLOCK =y" -- spaces around equals are invalid
     Warning: Ignoring "CONFIG_PARAVIRTTT_CLOCK = y" -- spaces around equals are invalid
     Warning: Ignoring "CONFIG_PARAVIRTTTT_CLOCK= y" -- spaces around equals are invalid

Signed-off-by: Bruce Ashfield <bruce.ashfield@windriver.com>

diff --git a/tools/kconf_check b/tools/kconf_check
--- a/tools/kconf_check
+++ b/tools/kconf_check
@@ -132,6 +132,15 @@ function sanitize_fragment ()
 		echo $LASTVAL|grep -q ' is not set$'
 		TAIL_OK=$?
 
+		echo $LASTVAL | grep -q '.* ='
+		if [ $? -eq 0 ]; then
+			space_before_equals=t
+		fi
+		echo $LASTVAL | grep -q '= '
+		if [ $? -eq 0 ]; then
+			space_after_equals=t
+		fi
+
 		grep -q -w $i $CLEAN_FRAG
 		if [ $? == 0 ] ; then	
 			echo Warning: Value of $i is defined multiple times within fragment $ORIG_FRAG:
@@ -141,6 +150,8 @@ function sanitize_fragment ()
 			# Enforce proper "# CONFIG_FOO is not set" syntax.
 			# LKC would ignore it anyway, so let them know.
 			echo Warning: Ignoring \"$LASTVAL\" -- invalid CONFIG syntax.
+		elif [ -n "$space_before_equals" ] || [ -n "$space_after_equals" ]; then
+			echo Warning: Ignoring \"$LASTVAL\" -- spaces around equals are invalid
 		else
 			echo $LASTVAL >> $CLEAN_FRAG
 		fi
