scc: exit on error
If there is an error in the processing of the input files, scc
should exit and inform the user.

scc is executed on a combined/preprocessed file and as a result
it doesn't have the granularity to see each input file individually.

Rather than moving preprocessing into scc (from spp), we can trap
the line number of the error and dump context around the line. This
gives the user a pointer to the input file and the specific line
that caused the problem.

Signed-off-by: Bruce Ashfield <bruce.ashfield@windriver.com>

diff --git a/tools/scc b/tools/scc
--- a/tools/scc
+++ b/tools/scc
@@ -238,18 +238,37 @@ process_file()
         done
 
         unset PATH
-        if [ -n "${verbose}" ]; then
-            eval . $in $outfile_append
-        else
-            # hide stderr if we aren't verbose
-            eval . $in $outfile_append 2> /dev/null
-        fi
-
-        if [ $? -ne 0 ]; then
-            echo "[ERROR]: processing of file $in failed"
-            exit 1
-        fi
+        (
+            set -e
+            eval . $in $outfile_append > /tmp/scc-output 2>&1
+        )
     )
+
+    if [ $? -ne 0 ]; then
+        echo "[ERROR]: processing of file $in failed"
+        cat /tmp/scc-output
+
+        # look for common errors so we can point to the right input file
+
+        # 1) /tmp/tmp.gfN6WsbDHN: line 403: cat: No such file or directory
+        #     "grep -oh" will only output what matches, which gets us "line 404: .."
+        #     cut gets us the second field, which is the line number
+        line=$(cat /tmp/scc-output | grep -oh "line.*:" | cut -f2 -d' ' | sed 's/://g')
+        if [ -n "$line" ]; then
+            let start_line=$line-20
+            let end_line=$line+10
+            if [ $start_line -lt 0 ]; then
+                start_line=0
+            fi
+            echo ""
+            echo "Context around the error is:"
+            echo ""
+            sed -n -e "$start_line,$end_line p" -e "$end_line q" $in | sed 's/^/    /'
+            echo ""
+            echo "See pre-processed file $in for more details"
+        fi
+        exit 1
+    fi
 
     return 0
 }
@@ -296,15 +315,6 @@ fi
 pre_processed_file="$outfile.pre"
 if [ -z "$outfile" ]; then
     pre_processed_file="$(mktemp)"
-fi
-
-# preprocess the files. This does things like make paths absolute, checks for
-# errors, etc.
-spp --force $intermediate_flags -o $pre_processed_file $include_paths $infiles
-if [ $? -ne 0 ]; then
-    err "ERROR: could not process input files: $infiles"
-    err "       See ${pre_processed_file} for details"
-    exit 1
 fi
 
 # load commands
@@ -370,8 +380,18 @@ if [ $? -eq 0 ]; then
     rm -f "${outdir}"/patch*.queue
 fi
 
+# preprocess the files.
+# This does things like make paths absolute, checks for errors, etc.
+spp --force $intermediate_flags -o $pre_processed_file $include_paths $infiles
+if [ $? -ne 0 ]; then
+    err "ERROR: could not process input files: $infiles"
+    err "       See ${pre_processed_file} for details"
+    exit 1
+fi
+
 eval header $outfile_start
 
+# process the files and produce artifacts
 process_file ${pre_processed_file}
 ret=$?
 if [ $ret -ne 0 ]; then
